### ISSUE TITLE
Arcade mode forfeit

### ISSUE THREAD

**Issue by acenturyandabit** [acenturyandabit/fortknight#31]
When you forfeit Arcade mode, the board continues to update.

**Comment by vicdjy** [comment]
Hi,
I just pushed to dannie's our-changes branch. I wonder if it works now?

**Comment by acenturyandabit** [comment]
Hmm, it looks like dannie's been keeping up to date with my master, which means that that's not a solution (and the one i suggested on the pull request won't work either!) 

If I were doing this normally I'd probably manually merge your PR so that the conflicts don't appear, but then you won't get credit for the pull request. Can you fork the current master and re-add your changes? 

Here's a diagram showing what happened and why it's difficult to fix:

![image](https://user-images.githubusercontent.com/33882353/102002834-8605b400-3d54-11eb-879a-798bb0ad4a9f.png)

(maybe you forked off from a different version but the general idea is the same)
 
This is what i think should be the right way to fix it (but does require work on your behalf:)

![image](https://user-images.githubusercontent.com/33882353/102002852-cb29e600-3d54-11eb-9d8d-95569933d6d1.png)

This way, you'll get credited for your changes and I won't have to redo my one, but you will have to redo your changes once you fork from master.

If it's too much trouble then let me know and i'll try and fix the merge manually :3

**Comment by acenturyandabit** [comment]
This issue is back up for grabs on account of vicdjy having finished her course.

**Comment by NammoPillai** [comment]
Hi @acenturyandabit, I'd like to take this issue up and resolve it
